before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: G9fF2WKhNeW1b2P7xPVZx4yUGe/LfkeLrnMCNh7rITx2R+quUkgrV5afpYI3x34OH+832zTF90IokTpROlLa30R/3sRMGprA7E0O7BC87dB3ZtGCWVDIDwO4PM9MX/IURbhcKwIZsn1bYuG8hUI70W4v4/YlQysFRxOlRJoPoEeCgqztEpySE1AYlTPBVjGJ2xpDSdm0sLu/jXD1jrSfQyEP8vuj15QKYlH5D+F7Twfx/v6czJTsm477rx44z9X3QsGL9mAH7RFf2fNoFxgGDywjxFeeqbDCkTITdtI4MzOecWiDxjuXfbw1G51XHH+JzMc05Gk2mkHKY5XWCGPIDoxncDZXFNEHIezhP6s4nf0ck8jHq49DqTAUgb4kqKiNqWlwVy4FQMqOkL6RZU0PDnuPMruzCAW+5ETKBymEyjIp1WsB7z+8zrp70beyDbqGZWX9CjsoabXxAReOtZOtXTezoHyvJe98pPgSuD+s2xotMPdHwYlePKSTfibeGTshy0KDzMn35b/29NBrg4odgUiRIJt4Tqudoh+9ImE6++QmBRGopVe3pROgNBT6MrCa6BuFKIHDmXbc8Ye9EipPIcxNEddQbyZX5VtRumyT223KkAy2bnsT9m+0OseM9JDqlRlzaR+319xt4OCLeHXD9bim/c/c9axeZMP2N+zuRkU= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
